2025-01-29 20:16:10,975 ERROR: Exception on /group/1 [GET] [in c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\routes.py", line 303, in group_detail
    return render_template(
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 1, in top-level template code
    {% extends ',newbase.html' %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\,newbase.html", line 63, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 24, in block 'content'
    <p class="profileJoinDate">Created {{group.creation_date.strftime('%B %d, %Y')}}</p>
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
2025-01-29 20:16:20,708 ERROR: Exception on /group/1 [GET] [in c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\routes.py", line 303, in group_detail
    return render_template(
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 1, in top-level template code
    {% extends ',newbase.html' %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\,newbase.html", line 63, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 24, in block 'content'
    <p class="profileJoinDate">Created {{group.creation_date.strftime('%B %d, %Y')}}</p>
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
2025-01-29 20:16:24,960 ERROR: Exception on /group/1 [GET] [in c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\routes.py", line 303, in group_detail
    return render_template(
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 1, in top-level template code
    {% extends ',newbase.html' %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\,newbase.html", line 63, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\coolb\Desktop\coding\roleplay hub\app\templates\group.html", line 24, in block 'content'
    <p class="profileJoinDate">Created {{group.creation_date.strftime('%B %d, %Y')}}</p>
  File "c:\users\coolb\desktop\coding\flasktest\venv\lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
2025-01-29 20:16:58,106 INFO: Microblog startup [in C:\Users\coolb\Desktop\coding\roleplay hub\app\__init__.py:56]
